name: p-3-pathfinder
version: 0.0.1
description: P³ is an clustered pathfinder algorithm for calculating the flight range in 3d space based on geographical terrain and glide angle
dependencies:

dev_dependencies:
#  unittest: any
